/**
 * 装备/道具定义
 */

const ITEMS = [
  {
    id: "straw_hat",
    name: "草帽",
    icon: "👒",
    slot: "head",
    effects: { hygiene: 2 },
    price: 10,
    desc: "防晒遮雨，摆摊必备",
    buyLocations: ["slum", "wholesaleMarket"],
  },
  {
    id: "work_gloves",
    name: "劳保手套",
    icon: "🧤",
    slot: "hand",
    effects: { physique: 3, injury: -0.02 },
    price: 15,
    desc: "体质+3，受伤概率-2%",
    buyLocations: ["wholesaleMarket", "construction"],
  },
  {
    id: "mask",
    name: "口罩",
    icon: "😷",
    slot: "head",
    effects: { hygiene: 5, illness: -0.03 },
    price: 5,
    desc: "卫生+5，生病概率-3%",
    buyLocations: ["slum", "wholesaleMarket", "commercialDist"],
  },
  {
    id: "sturdy_shoes",
    name: "解放鞋",
    icon: "👟",
    slot: "feet",
    effects: { agility: 3, fatigue: -5 },
    price: 25,
    desc: "敏捷+3，每日疲劳减少5",
    buyLocations: ["wholesaleMarket", "slum"],
  },
  {
    id: "backpack",
    name: "大背包",
    icon: "🎒",
    slot: "accessory",
    effects: { capacity: 10 },
    price: 40,
    desc: "背包容量+10kg",
    buyLocations: ["wholesaleMarket"],
  },
  {
    id: "work_uniform",
    name: "工作服",
    icon: "👔",
    slot: "body",
    effects: { hygiene: 3, fame: 2 },
    price: 35,
    desc: "卫生+3，名气+2，工作加成",
    buyLocations: ["wholesaleMarket", "commercialDist"],
  },
  {
    id: "safety_helmet",
    name: "安全帽",
    icon: "⛑️",
    slot: "head",
    effects: { injury: -0.05 },
    price: 20,
    desc: "工地受伤概率-5%",
    buyLocations: ["construction", "wholesaleMarket"],
  },
  {
    id: "smartphone",
    name: "智能手机",
    icon: "📱",
    slot: "accessory",
    effects: { intelligence: 2, fame: 3 },
    price: 500,
    desc: "智力+2，名气+3，拓宽视野",
    buyLocations: ["commercialDist", "techPark", "school"],
  },
  {
    id: "bicycle",
    name: "自行车",
    icon: "🚲",
    slot: null,
    effects: { agility: 5, fatigue_reduction: 10 },
    price: 200,
    desc: "敏捷+5，每日减疲劳10",
    buyLocations: ["wholesaleMarket", "commercialDist"],
  },
  {
    id: "cert_exam_book",
    name: "考证教材",
    icon: "📖",
    slot: null,
    effects: { skillStudy: 1.5 },
    price: 30,
    desc: "技能学习效率×1.5",
    buyLocations: ["school"],
  },
  {
    id: "backpack_basic",
    name: "帆布背包",
    icon: "🎒",
    slot: "accessory",
    effects: { capacity: 5 },
    price: 50,
    desc: "背包容量+5kg",
    buyLocations: ["wholesaleMarket"],
  },
  {
    id: "backpack_large",
    name: "大号旅行包",
    icon: "🎒",
    slot: "accessory",
    effects: { capacity: 15 },
    price: 150,
    desc: "背包容量+15kg",
    buyLocations: ["wholesaleMarket", "commercialDist"],
  },
  {
    id: "backpack_pro",
    name: "专业登山包",
    icon: "🎒",
    slot: "accessory",
    effects: { capacity: 30 },
    price: 400,
    desc: "背包容量+30kg",
    buyLocations: ["commercialDist"],
  },
  {
    id: "warm_coat",
    name: "厚棉衣",
    icon: "🧥",
    slot: "body",
    effects: { coldProtection: 20, comfort: 5 },
    price: 80,
    desc: "防寒+20，舒适度+5，冬天必备",
    buyLocations: ["wholesaleMarket", "commercialDist"],
  },
  {
    id: "sunscreen",
    name: "防晒霜",
    icon: "🧴",
    slot: "accessory",
    effects: { heatProtection: 15, hygiene: 3 },
    price: 25,
    desc: "防暑+15，夏天减少高温损耗",
    buyLocations: ["commercialDist", "slum"],
  },
  {
    id: "thermos",
    name: "保温杯",
    icon: "☕",
    slot: "accessory",
    effects: { fatigue: -3, hunger: 2 },
    price: 45,
    desc: "每日减疲劳3，维持体力",
    buyLocations: ["wholesaleMarket", "commercialDist"],
  },
];

function getItemById(itemId) {
  return ITEMS.find((i) => i.id === itemId) || null;
}

// ====== 住所层级定义 ======
const HOUSING_TIERS = [
  {
    tier: 0,
    name: "露宿街头",
    cost: 0,
    rent: 0,
    capacity: 20,
    fatigueRecovery: 15,
    desc: "天为被，地为床。碰上刮风下雨就惨了。",
    icon: "🌃",
    hygieneBonus: 0,
    happinessBonus: 0,
  },
  {
    tier: 1,
    name: "合租床位",
    cost: 300,
    rent: 12,
    capacity: 50,
    fatigueRecovery: 25,
    hygieneBonus: 5,
    desc: "城中村合租屋的一个床位，好歹有个遮风挡雨的地方。",
    icon: "🛏️",
    happinessBonus: 0,
  },
  {
    tier: 2,
    name: "单间",
    cost: 800,
    rent: 25,
    capacity: 100,
    fatigueRecovery: 35,
    hygieneBonus: 10,
    happinessBonus: 5,
    desc: "独立小单间，有床有柜子，私密多了。",
    icon: "🚪",
  },
  {
    tier: 3,
    name: "一居室",
    cost: 2000,
    rent: 50,
    capacity: 200,
    fatigueRecovery: 50,
    hygieneBonus: 15,
    happinessBonus: 10,
    desc: "正经的一室一厅，独立卫浴，生活质量质的飞跃。",
    icon: "🏠",
  },
  {
    tier: 4,
    name: "豪华公寓",
    cost: 10000,
    rent: 150,
    capacity: 400,
    fatigueRecovery: 70,
    hygieneBonus: 25,
    happinessBonus: 20,
    desc: "市中心高档公寓，健身房、游泳池一应俱全，人上人的住所。",
    icon: "🏙️",
  },
];

/** 获取当前住所信息 */
function getCurrentHousing(state) {
  return HOUSING_TIERS[state.housing?.tier || 0] || HOUSING_TIERS[0];
}
